import { useEffect, useState } from 'react';
import api from '../api/client';

export default function ComplexityLevels() {
  const [levels, setLevels] = useState([]);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const load = async () => {
      try {
        const res = await api.get('/complexity-levels');
        setLevels(res.data.data);
      } catch (err) {
        setError(err.response?.data?.message || 'Failed to load complexity levels');
      } finally {
        setLoading(false);
      }
    };
    load();
  }, []);

  if (loading) return <div>Loading...</div>;
  if (error) return <div className="alert alert-error">{error}</div>;

  return (
    <div>
      <h1>Complexity Levels</h1>
      <div className="text-muted mb-16">
        Fixed estimation hours — single source of truth. Total hours are generated by PostgreSQL.
      </div>
      <table>
        <thead>
          <tr>
            <th>Code</th>
            <th>Name</th>
            <th>Description</th>
            <th>Req. Review</th>
            <th>Code Dev</th>
            <th>Peer Review</th>
            <th>Bench Test</th>
            <th>Unit Test</th>
            <th>Total Hours</th>
          </tr>
        </thead>
        <tbody>
          {levels.map((l) => (
            <tr key={l.id}>
              <td><strong>{l.code}</strong></td>
              <td>{l.name}</td>
              <td className="text-muted">{l.description || '-'}</td>
              <td>{l.requirement_review_h}</td>
              <td>{l.code_development_h}</td>
              <td>{l.peer_review_fixing_h}</td>
              <td>{l.bench_testing_h}</td>
              <td>{l.unit_testing_h}</td>
              <td><strong>{l.total_hours}</strong></td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}